### ISSUE TITLE
Write solid tests

### ISSUE THREAD

**Issue by SerenadeX** [LyokoTech/LTMarkdownParser#10]
The parsing is still really buggy.  There are a handful of unit tests in here but I think we should have a lot more, and have the Example project have a working UITextView which we can put an attributed string into and test it manually. No reproduction steps

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description must include reproduction steps.
- Issue title must be in imperative, present tense (e.g. "add", "fix", "change").

[Click here](https://app.gitmagic.io/LyokoTech/TSSwiftMarkdownParser/10/91a66016-68ae-41ee-a580-0ec15842dc4f/8693d6ea-9921-4b6c-97b4-1d6df82ce2ea) for details. Leave a comment when you've fixed these errors and we will revalidate.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:
- Issue description must include reproduction steps.

[Click here](https://app.gitmagic.io/LyokoTech/TSSwiftMarkdownParser/10/91a66016-68ae-41ee-a580-0ec15842dc4f/8693d6ea-9921-4b6c-97b4-1d6df82ce2ea) for details.

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
