### ISSUE TITLE
Parse leveled lists

### ISSUE THREAD

**Issue by SerenadeX** [LyokoTech/LTMarkdownParser#12]
Right now it doesn't parsed lists with multiple levels e.g.
To reproduce, use the following markdown:

``` markdown
+ hello
  + hello
    + hello
+ hello
```

Which translates to:
- hello
  - hello
    - hello
- hello

We need to add that parsing so people can use multiple levels of indentation

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description must include reproduction steps.

[Click here](https://app.gitmagic.io/LyokoTech/TSSwiftMarkdownParser/12/91a66016-68ae-41ee-a580-0ec15842dc4f/cab34081-ec8c-4e2c-a75e-0c903ada7256) for details. Leave a comment when you've fixed these errors and we will revalidate.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by SerenadeX** [comment]
Fixed in #10

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
