### ISSUE TITLE
Index of out range while configuring custom font sizes

### ISSUE THREAD

**Issue by danieljvdm** [LyokoTech/LTMarkdownParser#21]
My code:
`let parser = LTMarkdownParser()
parser.listAttributes.append([NSFontAttributeName: UIFont.systemFontOfSize(20.0)])
let attString = parser.attributedStringFromMarkdown(model.prayerRequests)!`

The code crashes at line 65 while trying to access what seems to be attributesArray at [-1]

**Comment by danieljvdm** [comment]
It's actually not -1, you're just decrementing. Sorry a bit tired here.

**Comment by SerenadeX** [comment]
It's all good.  I'll take a look into it.
