### ISSUE TITLE
Set font size and styles

### ISSUE THREAD

**Issue by antonioreyna** [LyokoTech/LTMarkdownParser#29]
Hello, how can i set the styles for the normal paragraphs, and the bold and the headers each level?

thanks

**Comment by SerenadeX** [comment]
There are properties on the parser as you can see here: https://github.com/LyokoTech/LTMarkdownParser/blob/master/Pod/Classes/LTMarkdownParser.swift#L48

``` swift
    public var headerAttributes = [[String: AnyObject]]()
    public var listAttributes = [[String: AnyObject]]()
    public var numberedListAttributes = [[String: AnyObject]]()
    public var quoteAttributes = [[String: AnyObject]]()

    public var imageAttributes = [String: AnyObject]()
    public var linkAttributes = [String: AnyObject]()
    public var monospaceAttributes = [String: AnyObject]()
    public var strongAttributes = [String: AnyObject]()
    public var emphasisAttributes = [String: AnyObject]()
    public var strongAndEmphasisAttributes = [String: AnyObject]()
```

https://github.com/LyokoTech/LTMarkdownParser/blob/master/Pod/Classes/LTBaseParser.swift#L24

``` swift
    public var defaultAttributes = [String: AnyObject]()
```

Each property should hold attributes to be used for the AttributedString that is used for that type.

**Comment by antonioreyna** [comment]
thanks!! the fastest response i ever had thanks you!!

Just one more thing, do i have to set them each time i need to use the parser? or its a shared instance? singleton?

so i just do this once on appdelegate maybe or each time i need different parsing styles:

```
LTMarkdownParser.standardParser.defaultAttributes = [
            NSFontAttributeName: UIFont.systemFontOfSize(17.0),
            NSForegroundColorAttributeName: UIColor.mercurioBodyColor()
        ]
```

**Comment by SerenadeX** [comment]
You can make your own but there is a standard parser `standardParser` as a singleton.  You should only have to set it once and it will remember it for every time.  If it doesn't behave that way file an issue for it.
